### ISSUE TITLE
env.nix and flakes requiring all files to be in index.

### ISSUE THREAD

**Issue by heinwol** [GianniBuoni/nix-starter#1]
Sorry for bringing it up here, i'm just curious. How do you manage to evaluate the flake if some files are out of the index? I often face this problem. My usual decision is to keep the files in index, but set up a pre-commit hook to remove them. What do you do?

Thanks for your attention!

**Comment by ParmaGianni** [comment]
Hi, there! I do something very similar to what you're doing. I have a bash script that just runs `git add . -Nf && sudo nixos-rebuild switch --flake . && git reset`.

In the future, I plan on adding [SOPs Nix](https://github.com/Mic92/sops-nix) into my flake if I need a more CI friendly approach to secrets management.

**Comment by heinwol** [comment]
Thanks a lot for your answer!
